::: {.callout-note icon="false"}
#### Activity: Meeting Design + Facilitation Likes & Dislikes

**Group brainstorm**

Think about your own dominant thinking preference(s) - analytical, practical, relational, or experimental. Now think back to meetings and group processes you have been a part of. With this thinking preference in mind, what facilitation or meeting design techniques have you really appreciated? What allowed you to fully participate? Conversely, what did you find frustrating? 

- Open the EasyRetro collaborative whiteboard (link provided in the chat and in the notes doc)
- Find the column for the thinking preference you focused on
- Add the specific practices, tools, or techniques that you like by clicking the grey plus sign at the top of that column - one idea per card
- Feel free to emphasize other people's ideas by clicking the thumbs up
- Add a comment or question to any card by clicking the speech bubble

Now consider the expectations and preferences of the other thinking styles noted in the figure above and shared by your classmates. Are there any that you commonly overlook when you are planning a meeting? 

:::