::: {.callout-note icon="false"}
#### Activity: Small Group Exercise #2 - Emergent thinking practice

**Part 1 - Team Discussion & Co-Production**

- Assign a facilitator, notetaker and reporter
- Read through the list of options and begin with the step that seems most useful for your team's current needs. Work your way through as many of the steps as you can during the allotted time.
- _Create or refine a conceptual figure_ that captures how you are thinking about the system you are investigating
- Once you are satisfied with your conceptual figure:
    - Outline your key questions
    - Map your planned analyses to them
    - How are you going to answer each question with data?
    - If you were working with the tools we suggested last time to start outlining your analysis, this should build from there
- What are the \~3 key figures that would best illustrate your results?

**Part 2 - Report Out**

- Share what you developed with the whole group!
- After all groups have shared, offer suggestions to other groups and/or ask questions about the module.

:::
