project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - "*.qmd"

execute: 
  freeze: auto

website:
  title: "Synthesis Skills for Early Career Researchers"
  repo-url: https://github.com/lter/ssecr
  repo-actions: [issue] 
  favicon: topics/images/logo_lter.png
  google-analytics: "G-YGFW2JT4EY"
  sidebar: 
    title: "Modules"
    style: "docked"
    background: "light"
    border: true
    alignment: left
    collapse-level: 2
    contents:
      - text: "Course Overview"
        href: index.qmd
      - section: "Course Content"
        contents: 
            - text: "1. Synthesis Team Fundamentals"
              href: module-01.qmd
            - text: "2. Project Documentation & Organization"
              href: module-02.qmd
            - text: "3. Reproducible & Successful Teams"
              href: module-03.qmd
            - text: "4. Group Dialogue & Data Searches"
              href: module-04.qmd
            - text: "5. Qualities of Good Meetings & Data Logs"
              href: module-05.qmd
            - text: "6. Visualizing Data & Project Scope"
              href: module-06.qmd
            - text: "7. Plan the Work"
              href: module-07.qmd
            - text: "8. Build Consenus & Do Quality Control"
              href: module-08.qmd
            - text: "9. Tools for Meetings & Data Wrangling"
              href: module-09.qmd
            - text: "10. Intellectual Credit"
              href: module-10.qmd
            - text: "11. Group Stats Presentations"
              href: module-11.qmd
            - text: "12. Making Reports & Websites"
              href: module-12.qmd
            - text: "13. Looking Ahead & Spatial Data"
              href: module-13.qmd
            - text: "14. Share the Story"
              href: module-14.qmd
      - text: "Additional Resources"
        href: resources.qmd
  navbar:
    background: primary
    right: 
      - text: "Past Versions"
        menu:
            - text: "2024 (v1.0)"
              href: https://lter.github.io/ssecr-2024/
      - text: "Projects"
        href: projects.qmd 
      - text: "People"
        menu: 
            - text: "Instructors"
              href: instructors.qmd
            - text: "Fellows"
              href: fellows.qmd
      - icon: github
        href: https://github.com/lter/ssecr
  page-footer: 
    center: "Copyright 2026, LTER Network"
    background: secondary
  margin-footer: |
    ![NCEAS Logo](topics/images/logo_nceas.png){ width=40% }
    ![LTER Logo](topics/images/logo_lter.png){ width=34% }

format:
  html:
    code-overflow: scroll
    code-line-numbers: false
    code-copy: hover
    code-annotations: hover
    theme:
       light: _extensions/lter/lter_scss-theme/theme_lter-edu-light.scss
       dark: _extensions/lter/lter_scss-theme/theme_lter-edu-dark.scss
    mainfont: Open Sans
    toc: true
    link-external-newwindow: true
    link-external-icon: false

editor: source
