project:
  type: website
  execute-dir: project
  output-dir: docs

execute: 
  freeze: auto

website:
  title: "Synthesis Skills for Early Career Researchers"
  repo-url: https://github.com/lter/ssecr
  repo-actions: [issue]
  favicon: images/logo_lter.png
  google-analytics: "G-YGFW2JT4EY"
  sidebar: 
    title: "Modules"
    style: "docked"
    background: "light"
    border: true
    alignment: left
    collapse-level: 2
    contents:
      - text: "Course Overview"
        href: index.qmd
      - section: "Phase I -- Prepare"
        contents:
            - text: "Version Control"
              href: mod_version-control.qmd
            - text: "Reproducibility"
              href: mod_reproducibility.qmd
            - text: "Data Discovery"
              href: mod_data-disc.qmd
            - text: "Team Science"
              href: mod_team-sci.qmd
      - section: "Phase II -- Plan"
        contents:
            - text: "Inclusive Facilitation"
              href: mod_facilitation.qmd
            - text: "Data Wrangling"
              href: mod_wrangle.qmd
            - text: "Project Management"
              href: mod_project-mgmt.qmd
      - section: "Phase III -- Execute"
        contents:
            - text: "Supporting D.E.C. Thinking"
              href: mod_thinking.qmd
            - text: "Data Visualization"
              href: mod_data-viz.qmd
            - text: "Intellectual Credit"
              href: mod_credit.qmd
            - text: "Analysis & Modeling"
              href: mod_stats.qmd
      - section: "Phase IV -- Magnify"
        contents:
            - text: "Next Steps"
              href: mod_next-steps.qmd
      - section: "Phase V -- Share"
        contents:
            - text: "Communicating Findings"
              href: mod_findings.qmd
            - text: "Reproducible Reports"
              href: mod_reports.qmd
      - section: "Bonus Modules"
        contents:
            - text: "Spatial Data"
              href: mod_spatial.qmd
            - text: "Interactivity"
              href: mod_interactivity.qmd
  navbar:
    background: primary
    right: 
      - text: "Projects"
        menu:
            - text: "Milestones"
              href: proj_milestones.qmd
      - text: "Instructors"
        href: instructors.qmd
      - icon: github
        href: https://github.com/lter/ssecr
  page-footer: 
    center: "Copyright 2024, LTER Network"
    background: secondary
  margin-footer: |
    <img src="images/logo_nceas.png" width = "40%">
    <img src="images/logo_lter.png" width = "34%">

format:
  html:
    code-overflow: scroll
    code-line-numbers: false
    code-copy: hover
    theme:
       light: _extensions/lter/lter_scss-theme/theme_lter-edu-light.scss
       dark: _extensions/lter/lter_scss-theme/theme_lter-edu-dark.scss
    mainfont: Open Sans
    toc: true
    link-external-newwindow: true
    link-external-icon: false

editor: source
