project:
  type: website
  execute-dir: project
  output-dir: docs

execute: 
  freeze: auto

website:
  title: "Synthesis Skills for Early Career Researchers"
  repo-url: https://github.com/lter/ssecr
  repo-actions: [issue]
  google-analytics: "G-YGFW2JT4EY"
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
    right: 
      - text: "Instructors"
        menu: 
          - text: "Marty Downs"
            href: https://lternet.edu/
          - text: "Nick J Lyon"
            href: https://njlyon0.github.io/
  page-footer: 
    center: "Copyright 2024, LTER Network"
    background: secondary
  margin-footer: |
    <img src="images/logo_lter.png" width = "40%">
    <img src="images/logo_nceas.png" width = "40%">

format:
  html:
    theme:
       light: cosmo
       dark: cyborg
    css: styles.css
    toc: true
    link-external-newwindow: true
    link-external-icon: false

editor: source
