project:
  type: website
  execute-dir: project
  output-dir: docs

execute: 
  freeze: auto

website:
  title: "Synthesis Skills for Early Career Researchers"
  repo-url: https://github.com/lter/ssecr
  repo-actions: [issue]
  favicon: images/logo_lter.png
  google-analytics: "G-YGFW2JT4EY"
  sidebar: 
    title: "Modules"
    style: "docked"
    background: "light"
    border: true
    alignment: left
    collapse-level: 1
    contents:
      - text: "Course Overview"
        href: index.qmd
      - section: "Team Science Modules"
        contents: 
            - text: "Team Science"
              href: mod_team-sci.qmd
            - text: "Inclusive Facilitation"
              href: mod_facilitation.qmd
            - text: "Supporting Alt. Thinking"
              href: mod_thinking.qmd
            - text: "Intellectual Credit"
              href: mod_credit.qmd
            - text: "Project Management"
              href: mod_project-mgmt.qmd
            - text: "Logic Models"
              href: mod_logic-models.qmd
            - text: "Communicating Findings"
              href: mod_findings.qmd
      - section: "Quantitative Modules"
        contents:
            - text: "Reproducibile Code"
              href: mod_reproducibility.qmd
            - text: "Version Control"
              href: mod_version-control.qmd
            - text: "Data Discovery"
              href: mod_data-disc.qmd
            - text: "Data Visualization"
              href: mod_data-viz.qmd
            - text: "Data Wrangling"
              href: mod_wrangle.qmd
            - text: "Analysis & Modeling"
              href: mod_stats.qmd
            - text: "Spatial Data & Interactivity"
              href: mod_spatial.qmd
            - text: "Reproducible Reports"
              href: mod_reports.qmd
  navbar:
    background: primary
    right: 
      - text: "Instructors"
        menu: 
          - text: "Marty Downs"
            href: https://lternet.edu/
          - text: "Nick J Lyon"
            href: https://njlyon0.github.io/
  page-footer: 
    center: "Copyright 2024, LTER Network"
    background: secondary
  margin-footer: |
    <img src="images/logo_lter.png" width = "40%">
    <img src="images/logo_nceas.png" width = "40%">

format:
  html:
    code-overflow: scroll
    code-line-numbers: false
    code-copy: hover
    theme:
       light: theme_lter-light.scss
       dark: theme_lter-dark.scss
    mainfont: Lato
    toc: true
    link-external-newwindow: true
    link-external-icon: false

editor: source
