project:
  type: website
  execute-dir: project
  output-dir: docs

execute: 
  freeze: auto

website:
  title: "Synthesis Skills for Early Career Researchers"
  repo-url: https://github.com/lter/ssecr
  repo-actions: [issue]
  google-analytics: "G-YGFW2JT4EY"
  sidebar: 
    title: "Modules"
    style: "docked"
    background: "light"
    border: true
    alignment: left
    collapse-level: 1
    contents:
      - text: "Course Overview"
        href: index.qmd
      - section: "In-Person Week"
        contents: 
            - text: "Reproducibility"
            - text: "Version Control"
      - section: "Virtual 1"
        contents: 
            - text: "Data Discovery"
      - section: "Virtual 2"
        contents: 
            - text: "Team Science"
      - section: "Virtual 3"
        contents: 
            - text: "Inclusive Facilitation"
      - section: "Virtual 4"
        contents: 
            - text: "Data Visualization"
      - section: "Virtual 5"
        contents: 
            - text: "Supporting Divergent, Emergent, and Convergent Thinking"
            - text: "Data Wrangling"
            - text: "Intellectual Credit"
            - text: "Analysis & Modeling"
            - text: "Project Management"
            - text: "Logic Models"
            - text: "Spatial Data & Interactivity"
            - text: "Communicating Findings"
            - text: "Reproducible Reports"
  navbar:
    background: primary
    right: 
      - text: "Instructors"
        menu: 
          - text: "Marty Downs"
            href: https://lternet.edu/
          - text: "Nick J Lyon"
            href: https://njlyon0.github.io/
  page-footer: 
    center: "Copyright 2024, LTER Network"
    background: secondary
  margin-footer: |
    <img src="images/logo_lter.png" width = "40%">
    <img src="images/logo_nceas.png" width = "40%">

format:
  html:
    code-overflow: scroll
    code-line-numbers: false
    code-copy: hover
    theme:
       light: theme_lter-light.scss
       dark: theme_lter-dark.scss
    mainfont: Lato
    toc: true
    link-external-newwindow: true
    link-external-icon: false

editor: source
