---
title: "Course Overview"
---

Synthesis Skills for Early Career Researchers (SSECR; _\[SEE-ker\]_) is a course organized by the Long Term Ecological Research (LTER) Network. **This course aims to address the need for more comprehensive interpersonal and data skills in ecology.** You can find more information on SSECR at the [LTER Network page for the course](https://lternet.edu/ssecr/). 

The course is structured around small group synthesis projects, so that lessons are immediately applied to a synthesis problem that is relevant to learners and will likely result in a publication. Applicants will propose modest or exploratory synthesis projects as part of the application process. In addition to ideas stemming from participants' own work, the Network Office has compiled a small library of synthesis ideas in search of execution. SSECR begins with a number of activities aimed at establishing cohort cohesion and helping participants coalesce into 4-5 person project teams.

The Network Office has also recruited a corps of potential project mentors, who will be matched with participant projects and who agree to meet with students approximately five times per year. To apply to become a team mentor, go [here](https://lternet.edu/ssecr-mentor-application/).

Other specific course priorities include:

- Surface and test new synthesis ideas for feasibility
- Prepare more graduate students to be effective participants in/leaders of the synthesis projects
- Connect LTER graduate students across sites
- Develop intergenerational linkages around synthesis research

### Citing These Materials

We hope this course is useful to you and encourage you to use these materials! If you do use these materials, please use the following citation:

> Lyon, N.J., Kappel, C., Elmendorf, S., Kui, L., Maurer, G. E., De La Rosa, G., & Downs, M. (2025). Synthesis Skills for Early Career Researchers (SSECR) (v1.0). Zenodo. [https://doi.org/10.5281/zenodo.16969471](https://doi.org/10.5281/zenodo.16969471)

## Course Structure

:::{.panel-tabset}
### 2026-27 Structure


Course participants meet for two hours, weekly, at the same time each week. Each session covers a module (linked in the sidebar on the left of this page) that includes a blend of technical and interpersonal skills relevant for inclusive synthesis and team work on the chosen group projects.

Project groups will also meet at a time of their own choosing to work on projects. Project mentors are encouraged to participate in work sessions at least 4 times throughout the year.

### 2024-25 Structure

Course participants meet for three hours, weekly, at the same time each week. Sessions alternate between hands-on instruction in technical and soft skills that are relevant for inclusive synthesis and team work on the chosen group projects.

Each three-hour session will include 2 components:

1. **Networking (\~60 minutes)**: Presentation by one or more experienced synthesis scientists, describing why and how they conduct synthesis. This diverse group of researchers will be recruited from across the field and course participants will have ample time for discussion with each presenter.
2. **Instruction (~120 minutes)**: Each session will focus on a specific instructional topic, with technical skills, team-science skills, and communication topics interspersed throughout the year. The discussion will be limited to official course participants, but instructional materials for each topic will be available online, allowing individuals or site- or topic-based groups to follow along independently. 
    - Technical skills will build on earlier lessons and are not intended to be stand-alone modules.
The course will include social and leadership skills required to bring a synthesis project from idea to completion (or, for larger projects to completed proposal) and will include techniques for ensuring that multiple thinking and learning styles are respected and valued.

Project groups will also meet at a time of their own choosing to work on projects. Project mentors are encouraged to participate in work sessions at least 4 times throughout the year.

:::

## Course Scheduling

:::{.panel-tabset}
### 2026-27  Schedule

All dates are in 2026.

| **Date** | **Module** | **Primary Instructors** |
|:---:|:-------------|:---------|
| 9 / 10 | 1. Synthesis Team Fundamentals | {{< fa screwdriver-wrench >}} Nick Lyon <br> {{< fa people-group >}} _Marty Downs / Carrie Kappel_ (TBD) |
| 9 / 17 | 2. Project Documentation & Organization | {{< fa people-group >}} Nick Lyon <br> {{< fa screwdriver-wrench >}} _Sarah Elmendorf / Li Kui_ (TBD) |
| 9 / 24 | 3. Reproducible & Successful Teams | {{< fa screwdriver-wrench >}} Nick Lyon <br> {{< fa people-group >}} Carrie Kappel |
| 10 / 01 | 4. Group Dialogue & Data Searches | {{< fa people-group >}} Carrie Kappel <br> {{< fa screwdriver-wrench >}} Li Kui |
| 10 / 08 | 5. Qualities of Good Meetings & Data Logs | {{< fa people-group >}} Carrie Kappel <br> {{< fa screwdriver-wrench >}} Marty Downs |
| 10 / 15 | 6. Visualizing Data & Project Scope | {{< fa screwdriver-wrench >}} Sarah Elmendorf <br> {{< fa screwdriver-wrench >}} Nick Lyon <br> {{< fa people-group >}} Marty Downs |
| 10 / 22 | 7. Plan the Work | {{< fa people-group >}} Marty Downs <br> {{< fa screwdriver-wrench >}} Nick Lyon |
| 10 / 29 | 8. Build Consensus & Do Quality Control | {{< fa people-group >}} Carrie Kappel <br>  {{< fa screwdriver-wrench >}} Nick Lyon |
| 11 / 05 | 9. Tools for Meetings & Data Wrangling | {{< fa people-group >}} Carrie Kappel <br> {{< fa screwdriver-wrench >}} Nick Lyon |
| 11 / 12 | 10. Intellectual Credit | {{< fa people-group >}} Marty Downs |
| 11 / 19 | 11. Group Stats Presentations | **_SSECR Participants!_** |
| 11 / 26 | **No Class!** | -- |
| 12 / 03 | 12. Making Reports & Websites | {{< fa people-group >}} Marty Downs <br> {{< fa screwdriver-wrench >}} Nick Lyon |
| 12 / 10 | 13. Looking Ahead & Spatial Data | {{< fa people-group >}} Marty Downs <br> {{< fa screwdriver-wrench >}} Nick Lyon |
| 12 / 17  | 14. Share the Story | {{< fa people-group >}} _TBD_ |
| TBD | **Final Project Symposium** | _SSECR Participants!_ |
| TBD | Presentations on LTER Community Call | _SSECR Participants!_ |

### 2024-25 Schedule

| **Date** | **Module** | **Primary Instructor(s)** |
|:---:|:----------------------------|:---:|
| 9/5/24 | Version Control | [Nick Lyon](https://njlyon0.github.io/); [Angel Chen](https://angelchen7.github.io/) |
| 9/16-20/24 | Reproducibility Best Practices | [Nick Lyon](https://njlyon0.github.io/) |
| 10/3/24 | Data Discovery & Management | [Li Kui](https://orcid.org/0000-0002-5894-4907); [Marty Downs](https://orcid.org/0000-0003-2833-956X) |
| 10/17/24 | Team Sciences Practices | [Marty Downs](https://orcid.org/0000-0003-2833-956X); [Carrie Kappel](https://legacyworksgroup.com/team-content/carrie-kappel) |
| 10/31/24 | Inclusive Facilitation | [Carrie Kappel](https://legacyworksgroup.com/team-content/carrie-kappel) |
| 11/14/24 | Data Visualization & Exploration | [Sarah Elmendorf](https://www.colorado.edu/instaar/sarah-elmendorf); [Nick Lyon](https://njlyon0.github.io/) |
| 12/5/24 | Project Management | [Marty Downs](https://orcid.org/0000-0003-2833-956X) |
| 12/19/24 | Supporting Divergent, Emergent, and Convergent Thinking | [Carrie Kappel](https://legacyworksgroup.com/team-content/carrie-kappel) |
| 1/16/25 | Data Wrangling | [Nick Lyon](https://njlyon0.github.io/) |
| 1/30/25 | Authorship & Intellectual Credit | [Marty Downs](https://orcid.org/0000-0003-2833-956X) |
| 2/13/25 | **Canceled**
| 2/27/25 | Analysis & Modeling | [Nick Lyon](https://njlyon0.github.io/) |
| 3/13/25 | Next Steps & Logic Models | [Marty Downs](https://orcid.org/0000-0003-2833-956X) |
| 3/27/25 | Communicating Findings | [Gabriel de la Rosa](https://www.gabrieldelarosa.com/) |
| 4/10/25 | Reproducible Reports | [Nick Lyon](https://njlyon0.github.io/) |
| 4/24/25 | _Bonus Module / Optional Prep_ | TBD |
| 5/8/25 | _Optional Prep_ | TBD |
| 5/22/25 | **Final Project Symposium** | _SSECR Participants!_ |
| 5/28/25 | Public Presentations on LTER Community Call | _SSECR Participants!_ |

:::

## Course Policies

### Attendance

{{< include policy/attendance.qmd >}}

### Usability, Accessibility, and Design

{{< include policy/usability.qmd >}}

### Name, Gender Identity, and/or Gender Expression

{{< include policy/pronouns.qmd >}}

### Code of Conduct

{{< include policy/conduct.qmd >}}
