---
title: "Working with Spatial Data"
code-annotations: hover
---

## Overview

Synthesis projects often have need of spatial datasets. At its simplest, it can be helpful to have a map of the original project locations including in the synthesis dataset. In more complex instances you want to extract spatial data within a certain area of sampling locations. Regardless of 'why' you're using spatial data, it may come up during your primary or synthesis work and thus deserves consideration in this course's materials. There are _many_ modes of working with spatial data, and not all of these tools require coding literacy but for consistency with the rest of the modules **this module will focus on _scripted_ approaches to interacting with spatial data**.

## Learning Objectives

After completing this topic you will be able to: 

- <u>Define</u> the difference between the two major types of spatial data
- <u>Manipulate</u> spatial data with R
- <u>Integrate</u> spatial data with tabular data

## Needed Packages

If you'd like to follow along with the code chunks included throughout this module, you'll need to install the following packages:

```{r install-pkgs}
#| eval: false

# Note that these lines only need to be run once per computer
## So you can skip this step if you've installed these before
install.packages("tidyverse")
install.packages("sf")
install.packages("terra")
```

## Types of Spatial Data

There are two main types of spatial data: vector and raster. You may have cause to work either or both so we'll describe both (and the packages they require) in the tabs below.

:::{.panel-tabset}
### Vector Data

Data stored as polygons / shapes


### Raster Data

Data stored as pixels

:::

## Coordinate Reference Systems

A fundamental problem in spatial data is how to project data collected on a nearly spherical planet onto a two-dimensional plane. This has been solved--or at least clarified--by the use of <u>C</u>oordinate <u>R</u>eference <u>S</u>ystems (a.k.a. "CRS"). The CRS defines the following information:

- 


## Making Maps





## Extracting Spatial Data





## Additional Spatial Resources

### Papers & Documents

- 

### Workshops & Courses

- The Carpentries' [Introduction to Geospatial Raster & Vector Data with R](https://datacarpentry.org/r-raster-vector-geospatial/)
- The Carpentries' [Introduction to R for Geospatial Data](https://datacarpentry.org/r-intro-geospatial/index.html)
- Arctic Data Center's [Spatial and Image Data Using GeoPandas](https://learning.nceas.ucsb.edu/2023-03-arctic/sections/geopandas.html) chapter of their Scalable Computing course
- Jason Flower's (UC Santa Barbara) [Introduction to rasters with `terra`](https://jflowernet.github.io/intro-terra-ecodatascience/)
- King, R. [Spatial Data Visualization](https://github.com/king0708/spatial-data-viz) workshop

### Websites

- NASA's <u>App</u>lication for <u>E</u>xtracting and <u>E</u>xploring <u>A</u>nalysis <u>R</u>eady <u>S</u>amples [(AppEEARS) Portal](https://appeears.earthdatacloud.nasa.gov/)
