---
title: "Project Management & Logic Models"
---

## Overview

Team science works best when all participants know when and how they can contribute. Effective project management allows team members to work on many tasks asynchronously, without losing track of the overall context or the progress in related areas of the project. The effort required is returned many times in avoided frustration and unnecessary backtracking and duplication of effort. Developing an explicit logic model *as a team* helps identify and resolve differences in the mental models and assumptions that team members from diverse disciplines bring to an analysis. It also helps clarify all of the information that will be needed and the appropriate order of steps.

## Learning Objectives

After completing this module you will be able to: 

- <u>Articulate</u> key principles of project management
- <u>Develop</u> (or refine) the project management framework for your team project
- <u>Define</u> common approaches for logic models
- <u>Identify</u> and make explicit internal logical leaps

## Preparation

TBD (<u>T</u>o <u>B</u>e <u>D</u>etermined)

## Networking Session

::: panel-tabset
### 2024 Guests

The [Silica Exports synthesis working group](https://lternet.edu/working-groups/from-poles-to-tropics-a-multi-biome-synthesis-investigating-the-controls-on-river-si-exports/) faced a number of coordination challenges -- including work context (federal agency and academia), widely dispersed geographic locations (participants and data from 6 continents), and multiple data repositories. Their approach to project management helped them to overcome these obstacles and assemble an exceptional database that is broadly available and a set of novel analyses. 

-  [Kathi Jo Jankowski](https://www.usgs.gov/staff-profiles/kathi-jo-jankowski), Research Ecologist, Upper Midwest Environmental Sciences Center, U.S. Geological Survey
:::

## Module Content



## Additional Resources

### Papers & Documents

- 

### Workshops & Courses

- LTER Scientific Computing Team. [Collaborative Coding with GitHub: Issues](https://lter.github.io/workshop-github/issues.html). **2024**.
- LTER Scientific Computing Team. [Collaborative Coding with GitHub: Milestones](https://lter.github.io/workshop-github/milestones.html). **2024**.
- LTER Scientific Computing Team. [Collaborative Coding with GitHub: Projects](https://lter.github.io/workshop-github/projects.html). **2024**.
- NCEAS Learning Hub & Delta Stewardship Council. [Open Science Synthesis: Logic Models and Synthesis Development](https://learning.nceas.ucsb.edu/2021-09-delta/session-8-hands-on-logic-models-and-synthesis-development.html). **2021**.

### Websites

- 
