---
title: "Communicating Findings"
---

## Overview

Under Construction, stay tuned!

## Learning Objectives

After completing this module you will be able to: 

- <u>Define</u> elements of (in)effective communication
- <u>Identify</u> relevant audiences for a particular work
- <u>Determine</u> audience motivations and interest
- <u>Translate</u> communication into various formats based on efficacy with target group

## Preparation

None required.

## Networking Session

::: panel-tabset
### 2024 Guests

[Dr. Alex Phillips](https://www.alexandraatleephillips.com/), Assistant Teaching Professor, Bren School of Environmental Science and Management, UC Santa Barbara

As a former NCEAS communications officer and a AAAS science and technology policy fellow in climate science, Alex brings extensive experience in making scientific synthesis engaging. Her teaching and research focuses on environmental communication to students, scientists, policymakers, and the public. She was also a postdoc at UCSB and the Large Lakes Observatory at University of Minnesota, Duluth where she investigated carbon sequestration in Lake Superior. She holds a PhD from Caltech in geochemistry, where she studied sulfur and carbon cycling in lakes and oceans.

:::

## Effective Communication



## Publishing Code, Data, and Results




## Data Management Plans


## Additional Resources

### Papers & Documents

- 

### Workshops & Courses


- NCEAS Learning Hub & Delta Stewardship Council. [Open Science Synthesis: Communicating Your Science ](https://learning.nceas.ucsb.edu/2023-10-delta/session_02.html). **2023**.

### Websites

- COMPASS. [The Message Box](https://www.compassscicomm.org/leadership-development/the-message-box/)
