---
title: "Team Science Practices"
---

## Overview

In this module, we'll dive into some of the literature underlying our recommended team science practices (the science of team science). We'll also explore some of the more common types of conflicts that arise in synthesis work and ways to anticipate, prevent (when possible), and resolve those conflicts. 

## Learning Objectives

After completing this module you will be able to: 

- <u>Interpret</u> and enact current best practices in team science
- <u>Identify</u> different interaction styles and the effect they have on group dynamics
- <u>Identify</u> benefits (and potential costs of) diverse teams
- <u>Describe</u> ways to mitigate costs of diverse teams
- <u>Explain</u> methods for improving the experience of virtual participants on hybrid teams 

## Preparation

Each project group should:

- Plan on providing a project summary and update on recent progress and any questions/issues that are arising
- Finish their internal ground rules (if not already complete)

## Panel Discussion

We'll begin this session's discussion with a conversation among participants in a recent synthesis group that tackled a particularly broad disciplinary stretch. The [Synthesizing population and community synchrony to understand drivers of ecological stability across LTER sites](https://lternet.edu/working-groups/synthesizing-population-and-community-synchrony-to-understand-drivers-of-ecological-stability-across-lter-sites/) brought together methematicians, modelers, and empiricists to apply novel analytical strategies to understanding the impact of population fluctuations. 

Panelists will briefly introduce themselves and their experience with the synthesis group, which encountered a variety of challenges in their work. Ultimately, they produced several effective and well-received papers, but they had to introduce some innovations in working group approach to get there.


::: panel-tabset
### 2024 Panelists

-   Dr. [Lauren Hallett](https://ie2.uoregon.edu/people/hallett/), Associate Professor, University of Oregon
-   Dr. [Max Castorani](https://castorani.evsc.virginia.edu/), Associate Professor, University of Virginia
-   Dr. [Jonathan Walter](https://sites.google.com/site/jwalterecology/home), Senior Researcher, [Center for Watershed Sciences](https://watershed.ucdavis.edu/), University of California, Davis
:::

## Module Content

Under Construction, stay tuned!

## Additional Resources

### Papers & Documents

- Bates, A.E. _et al._, [Overcome Imposter Syndrome: Contribute to Working Groups and Build Strong Networks](https://www.sciencedirect.com/science/article/pii/S0006320724001289?via%3Dihub). **2024**. _Biological Conservation_
- Peterson, D.M., _et al._, [Team Science: A Syllabus for Success on Big Projects](https://onlinelibrary.wiley.com/doi/10.1002/ece3.10343). **2023**. _Ecology and Evolution_
- Gaynor, K.M., _et al._, [Ten Simple Rules to Cultivate Belonging in Collaborative Data Science Research Teams](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1010567). **2022**. _PLoS Computational Biology_
- Deutsch, L., _et al._, [Leading Inter- and Transdisciplinary Research: Lessons from Applying Theories of Change to a Strategic Research Program](https://www.sciencedirect.com/science/article/pii/S146290112100054X?via%3Dihub). **2021**. _Environmental Science & Policy_
- Farrell, K.J. _et al._, [Training  Macrosystems Scientists Requires Both Interpersonal and Technical Skills](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/fee.2287). **2021**. _Frontiers in Ecology and the Environment_
- Hampton, S.E. & Parker, J.N. [Collaboration and Productivity in Scientific Synthesis](https://academic.oup.com/bioscience/article/61/11/900/223655). **2011**. _BioScience_
- Lowman, H. et al., [Collaborative consortia can boost postdoctoral workforce development](https://doi.org/10.1073/pnas.2401812121). **2024** _PNAS_

### Workshops & Courses

- Liberatore, A. [Developing a Successful Team: Concepts and Strategies to Navigate Change and Conflict Together](https://docs.google.com/presentation/d/1xbT59ULxJhV-QF4FAeU7EYkOGGzzrIjTlDEULlNyerw/edit#slide=id.p). **2024**.
- National Center for Ecological Analysis and Synthesis (NCEAS) Learning Hub & Delta Stewardship Council. [Open Science Synthesis: Team Science for Synthesis](https://learning.nceas.ucsb.edu/2023-09-ucsb-faculty/session_02.html). **2023**.
- Delta Stewardship Council. [Open Science Synthesis: Thinking Preferences](https://learning.nceas.ucsb.edu/2021-09-delta/session-6-collaboration-practices.html#thinking-preferences). **2021**.

### Websites

- Lahr, Heather [How to effectively engage teams in interdisciplinary collaborations](How to effectively engage teams in interdisciplinary collaborations). **2024**
