---
title: "Inclusive Facilitation"
---

## Overview

Under Construction, stay tuned!

## Learning Objectives

After completing this module you will be able to: 

- <u>Describe</u> benefits of encouraging full, thoughtful, engaged participation
- <u>Identify</u> methods for ensuring equitable access to participation in a team setting
- <u>Identify</u> one activity that privileges each thinking style

## Preparation

Complete Phase 1 course survey

## Networking Conversation

Inclusive facilitation is challenging, even when facilitators and participants are quite similar, but when their backgrounds, ages, or positions are different, it can be even more so. This class we'll talk with Mack White, a graduate student who is serving as PI for the [Marine Consumer Nutrient Dynamics synthesis group](https://lternet.edu/working-groups/marine-consumer-nutrient-dynamics/). He'll address approaches for inclusive facilitation broadly, as well as the special challenges inherent in facilitating a group of colleagues who are more senior and experienced than he is.

:::panel-tabset

### 2024 Guests

[Mack White](https://crestcache.fiu.edu/about/students/profiles/white-mackenzie-mack.html#), PhD studnet with Dr. Jennifer Rehage, Florida International University  

:::

## Module Content

**Coming soon!**


## Additional Resources

### Papers & Documents

- Kaner, S. [Facilitator's Guide to Participatory Decision-Making (Revised)](https://bookshop.org/p/books/facilitator-s-guide-to-participatory-decision-making-sam-kaner/11179446?ean=9781118404959). **2014**.
- Woodley, L., Pratt, K., & East, J. (2021). [A guide to using virtual events to facilitate community building: Making a PACT for more engaging virtual meetings and events](https://doi.org/10.5281/zenodo.4987666). Zenodo.

### Workshops & Courses

- 

### Websites

- [Liberating Structures: Including and Uleashing Everyone](https://www.liberatingstructures.com/)
