---
title: "Next Steps & Logic Models"
---

## Overview

Whether group members are excited about continuing to work together or ready to go their own ways, a little thought and discussion about how group members envision their next steps can set you up for success. In this module, we discuss ways to help ensure that your work is recognized and cited, talk about expectations going forward, and begin thinking about how continued work could be supported.

## Learning Objectives

After completing this module you will be able to: 

- <u>Identify</u> needed data and target audience(s)
- <u>Articulate</u> connection(s) between proposed investigation and beneficial outcome
- <u>Write</u> polished, funding-worthy proposals

## Preparation

No specific preparation required.

## Networking Session

::: panel-tabset
### 2025 Guests

[Dr. Cristina Portales Reyes](https://www.portalesbiodiversitylab.com/), Assistant Professor, St. Louis University
Cristy participated in the [synchrony synthesis working group](https://www.portalesbiodiversitylab.com/) as a graduate student at the University of Minnesota. That group had barely finished when she proposed (and was awarded) a working group that she now leads on difficult-to-reverse [ecosystem transitions](https://lternet.edu/working-groups/ecosystem-transitions-increased-variability-and-regime-shifts/). 

[Dr. Laureano Gherardi](https://vcresearch.berkeley.edu/faculty/laureano-gherardi), Assistant Professor, Berkeley University
Laureano also participated in the [synchrony synthesis working group](https://lternet.edu/working-groups/synthesizing-population-and-community-synchrony-to-understand-drivers-of-ecological-stability-across-lter-sites/) as a graduate student at Arizona State University and followed it up with not one, but three additional synthesis groups:  [ecosystem transitions](https://lternet.edu/working-groups/ecosystem-transitions-increased-variability-and-regime-shifts/), [global drought effects](https://lternet.edu/working-groups/a-global-synthesis-of-multi-year-drought-effects-on-terrestrial-ecosystems/), and [resilience and management](https://lternet.edu/working-groups/resilience-and-management/).

:::

## ...







## Additional Resources

### Papers & Documents

- Deutsch L., _et al._, [Leading Inter- and Transdisciplinary Research: Lessons from Applying Theories of Change to a Strategic Research Program](https://www.sciencedirect.com/science/article/pii/S146290112100054X?via%3Dihub). **2021**. _Environmental Science & Policy_

### Workshops & Courses

- 

### Websites

- Shabanov, I. (\@Artifexx) [Tweet on logic models](https://x.com/artifexx/status/1798936726788051403?s=51&t=TCar5jaRTW3NNuD_rXT8Pg). **2024**.
