---
title: "Working Collaboratively"
---

At this point, you may be holding some discussions among the team that could be challenging. Today we'll give you some tools on understanding team dynamics and navigating conflict (hopefully before you need them) then we'll circle back in later classes to provide some broader context. Similarly, you are probably already writing preliminary code--or at least such code is clearly approaching in your near future. We'll discuss some facets of how that code can be made as reproducible as possible so that even these 'rough draft' code files are interpretable by others. 

:::{.callout-note icon="false" collapse="false"}
### {{< fa file-pen >}} Pre-Class Preparation

There is no specific pre-class preparation for this module!

:::

{{< include topics/participation-benefits-activity.qmd >}}

{{< include topics/team-sci.qmd >}}

{{< include topics/participation-benefits.qmd >}}

{{< include topics/team-conflict.qmd >}}

{{< include topics/participation-access.qmd >}}

{{< include topics/reproducible-coding.qmd >}}

{{< include topics/code-comments.qmd >}}

{{< include topics/consider-functions.qmd >}}

# Prep Work for Next Module

:::{.callout-note icon="false" collapse="false"}
### {{< fa file-pen >}} Pre-Class Preparation

#### **Before we meet to cover the next module**, do all of the work in the callout like this one at the top of that module's page!
:::
