---
title: "Exploring Diversity & Visualization"
bibliography: 
    - topics/references/viz-meet_refs.bib
---

Today, we'll provide you some tools and best practices for making sure that your meetings are impactful, necessary, and accessible to all participants so that meeting with the group doesn't cost you any momentum! We'll then follow up with a quick primer on ggplot and how to leverage data visualization for exploring data. While there are many ways of evaluating whether data are useful, visualization is one of the quicker methods. That visualization can also be useful at virtually all other stages of your project is a happy accident of which you can take advantage. 

:::{.callout-note icon="false" collapse="false"}
### {{< fa file-pen >}} Pre-Class Preparation

On your own, consider the following:

- What's one thing your group is doing really well to ensure all team members can participate in meetings and project work?
- What's one area where your team has room to improve its inclusive facilitation practices?
- What could you personally be doing better to ensure equal access to participation?

Take notes on your thoughts because we'll discuss more in small groups and as a class when we cover this module!

Please also identify and download one potential dataset your group is considering including in your synthesis to use in class today. If you haven't identified any yet, select a dataset from the [lterdatasampler](https://lter.github.io/lterdatasampler/) to practice with instead.
:::


{{< include topics/team-diversity.qmd >}}

{{< include topics/team-support.qmd >}}

{{< include topics/viz-synthesis.qmd >}}

{{< include topics/viz-draw.qmd >}}

{{< include topics/viz-ggplot2-core.qmd >}}

{{< include topics/viz-ggplot2-multipanel.qmd >}}

{{< include topics/viz-exploration.qmd >}}

# Prep Work for Next Module

:::{.callout-note icon="false" collapse="false"}
### {{< fa file-pen >}} Pre-Class Preparation

#### **Before we meet to cover the next module**, do all of the work in the callout like this one at the top of that module's page!
:::



