---
title: "Ensuring Equitable Intellectual Credit"
---

Group synthesis requires many types of contributions, from raw data to idea generation, analysis, group organization, figure development, conceptualizing, writing, and editing. Often, little of this work is directly compensated. Conflicts and misunderstandings about what contributions earn authorship arise--especially in the absence of a clearly-articulated policy on intellectual credit. 

In this module we will discuss a few models for aligning expectations around intellectual credit and how they may differ depending on the participants and the particular product the group is developing. We'll also take some time for project groups to develop or refine their own intellect credit policies.

:::{.callout-note icon="false" collapse="false"}
### {{< fa file-pen >}} Pre-Class Preparation

- No specific pre-class preparation for this module!

:::

{{< include topics/credit-background.qmd >}}

{{< include topics/credit-optin-optout.qmd >}}

{{< include topics/author-policy.qmd >}}

{{< include topics/credit-future.qmd >}}
