---
title: "Planning the Work"
---

As your project work has advanced, your group may find that it's useful to articulate specific sub-goals or desired products. This module will cover some ways of identifying those outcomes and the tasks that are prerequisite to those ends. We'll also discuss how you might go about "harmonizing" (i.e., standardizing and--possibly--combining) the data you have found and what initial exploratory steps might be useful.

:::{.callout-note icon="false" collapse="false"}
### {{< fa file-pen >}} Pre-Class Preparation

**Complete your first draft of the data inventory!** This should include (at least) 3-5 datasets and all columns that you know at this point are likely to be useful--even if we expect that you may discover additional useful pieces of information to record as your project continues.

:::

{{< include topics/proj-analysis.qmd >}}

{{< include topics/proj-mgmt-plan.qmd >}}

{{< include topics/workflow-plan.qmd >}}

{{< include topics/harmonize-data.qmd >}}

{{< include topics/wrangle-explore.qmd >}}

# Prep Work for Next Module

:::{.callout-note icon="false" collapse="false"}
### {{< fa file-pen >}} Pre-Class Preparation

#### **Before we meet to cover the next module**, do all of the work in the callout like this one at the top of that module's page!
:::
