---
title: "Synthesis Research Projects"
---

One of the primary facets of the course is that Synthesis Fellows assemble into project teams to collaboratively identify their research questions and pursue novel synthesis projects throughout the course. See below for brief descriptions of each project team as well as a high-level summary of project milestones to help teams stay on track.

## Project Teams

Team members and project mentors are listed in reverse alphabetical order by last name and their LTER site affiliation is indicated in parentheses. For more information on LTER sites, check out the [site profiles](https://lternet.edu/site/) section of the Network website.

:::{.panel-tabset}
## 2026 Teams

### Ecological Efficacy of Climate Adaptation Actions

<u>Team Members</u>: **TBD**

<u>Science Mentor(s)</u>: [Dr. Sarah Weiskopf](https://www.usgs.gov/staff-profiles/sarah-weiskopf), Research Ecologist, National Climate Adaptation Science Center, US Geological Survey and [Dr. Meagan Oldfather](https://www.usgs.gov/staff-profiles/meagan-oldfather), Biologist, USGS North Central Climate Adaptation Science Center

{{< fa brands github >}} <u>GitHub Repository</u>: [lter / **ssecr-eco-efficacy**](https://github.com/lter/ssecr-eco-efficacy)

### Shifting Baselines at Global Change Experiments

<u>Team Members</u>: **TBD**

<u>Science Mentor(s)</u>: [Dr. Pam Templer](https://people.bu.edu/ptempler/), Distinguished Professor, Boston University & **TBD**

{{< fa brands github >}} <u>GitHub Repository</u>: [lter / **ssecr-shifting-bases**](https://github.com/lter/ssecr-shifting-bases)

### Arctic-Boreal Phenology

<u>Team Members</u>: **TBD**

<u>Science Mentor(s)</u>: **TBD**

{{< fa brands github >}} <u>GitHub Repository</u>: [lter / **ssecr-boreal-phenology**](https://github.com/lter/ssecr-boreal-phenology)

### Detecting Time Lags in Ecosystem Nutrient Inputs & Outputs

<u>Team Members</u>: **TBD**

<u>Science Mentor(s)</u>: [Dr. Adam Wymore](https://ecosheds.weebly.com/), Associate Professor, University of New Hampshire

{{< fa brands github >}} <u>GitHub Repository</u>: [lter / **ssecr-time-lags**](https://github.com/lter/ssecr-time-lags)

### Biodiversity as a Mediator of Global Change Effects on Ecosystem Functioning

<u>Team Members</u>: **TBD**

<u>Science Mentor(s)</u>: [Dr. Laura Dee](https://www.lauraedee.com/), University of Colorado-Boulder and [Dr. Tim Ohlert](https://tim-ecology.weebly.com/), Postdoctoral Associate, University of Colorado, Boulder

{{< fa brands github >}} <u>GitHub Repository</u>: [lter / **ssecr-biodiv-mediator**](https://github.com/lter/ssecr-biodiv-mediator)

## 2024-25 Teams

### Carbon Cycling Responses Across Spatiotemporal Scales

<u>Team Members</u>: **Yiyang Xu** (Plum Island Ecosystems; Virginia Coast Reserve), **Taylor Walker** (Moorea Coral Reef), **Carla López Lloreda** (Luquillo), **Guopeng Liang** (Cedar Creek), **Jon Gewirtzman** (Harvard Forest; Florida Coastal Everglades), **Julie Gan** (Arctic), **Ricky Brokaw** (Santa Barbara Coastal)

<u>Science Mentor(s)</u>: [**Will Wieder**](https://staff.ucar.edu/users/wwieder) (Niwot Ridge), [**Marci Litvak**](https://www.litvaklab.org/) (Sevilleta)

{{< fa brands github >}} <u>GitHub Repository</u>: [lter / **ssecr-c-cycling**](https://github.com/lter/ssecr-c-cycling)

<u>Project Question(s)</u>: How does carbon cycling respond to environmental change (in experimental manipulations and to natural disturbances)? How does the duration of the disturbance influence how we model carbon cycling projections in the future across ecosystems? Further, what are the mechanisms driving these responses?

### <u>S</u>ynchrony of <u>A</u>bove & <u>B</u>elowground <u>R</u>esponses Across <u>E</u>cosystems (SABRE)

<u>Team Members</u>: **Smriti Pehim Limbu** (Konza Prairie), **McKinley Nevins** (Andrews Forest), **Francis Chaves Rodriguez** (Konza Prairie), **Ashley Bulseco** (Plum Island Ecosystems), **Abigail Borgmeier** (McMurdo Dry Valleys; Sevilleta)

<u>Science Mentor(s)</u>: [**Serita Frey**](https://colsa.unh.edu/person/serita-frey) (Harvard Forest), [**Meghan Avolio**](https://avoliolab.weebly.com/) (Konza Prairie)

{{< fa globe >}} <u>Team Website</u>: [francis-chaves.github.io/above-belowground-coupling](https://francis-chaves.github.io/Above-Belowground-Coupling/)

{{< fa brands github >}} <u>GitHub Repository</u>: [lter / **ssecr-above-belowground-coupling**](https://github.com/lter/ssecr-above-belowground-coupling)

<u>Project Question(s)</u>: Are above and belowground communities synchronous or decoupled in response to temperature and precipitation variability?

### Diversity-Stability Relationships

<u>Team Members</u>: **Junna Wang** (Harvard Forest), **James Sturges** (Florida Coastal Everglades), **Kelsey Solomon** (Florida Coastal Everglades; Coweeta), **Julianna Renzi** (Moorea Coral Reef), **Pooja Panwar** (Hubbard Brook), **Katherine Hulting** (Kellogg Biological Station), **Noam Altman-Kurosaki** (Moorea Coral Reef)

<u>Science Mentor(s)</u>: [**Forest Isbell**](https://biodiversitylab.umn.edu/) (Cedar Creek), [**Laura Dee**](https://www.lauraedee.com/) (Niwot Ridge)

{{< fa brands github >}} <u>GitHub Repository</u>: [lter / **ssecr-diversity-stability**](https://github.com/lter/ssecr-diversity-stability)

<u>Project Question(s)</u>: How does the strength and direction of diversity-stability relationships vary (1) among ecosystems and (2) between ecosystem-level and community-level stability?

### Effects of Environmental Drivers Across Ecological Scales

<u>Team Members</u>: **Bethany Williams**, **Sierra Perez** (Kellogg Biological Station; Cedar Creek), **Evald Maceno** (Luquillo), **Joey Krieger Lodge** (Niwot Ridge), **Jeremy Collings** (Andrews Forest), **Allison Case**

<u>Science Mentor(s)</u>: [**Zach Feiner**](https://zsfeiner.github.io/) (North Temperate Lakes)

{{< fa brands github >}} <u>GitHub Repository</u>: [lter / **ssecr-driver-scales**](https://github.com/lter/ssecr-driver-scales)

<u>Project Question(s)</u>: Are the effects of environmental drivers consistent across ecological scales?

:::

## Project Milestones


The below benchmarks are meant to provide a _rough_ progress estimate of how your project "should" progress during the course. Your group may at times be ahead of these milestones or behind at others so **please use this resource as general guidance rather than specific timing requirements.**

:::{.panel-tabset}
#### 2024-25 Milestones

### Months 1-2 (Sep./Oct.)

- Literature review well underway and/or complete
- Good progress finding data (50-75% known needed data found)
- Collaboratively identified ground rules, communication and coordination plan, and project roles

### Month 3 (Nov.)

- Draft a plan for your analyses
    - Looking for sufficient detail that you can articulate what harmonized data might be needed
- Largely finished finding data
- Exploratory visualization

### Month 4 (Dec.)

- Strong progress harmonizing your data
- Internal project status check-in and team dynamics assessment

### Month 5 (Jan.) 

- Finish harmonizing data
- Revize planned analyses
    - Harmonizing the data will help inform what questions you want to (or are able to) ask

### Month 6 (Feb.)

- Run and interpret preliminary analyses
- Consider drafting an 'extended figures document' that summarizes key messages and includes rough draft figures)
- Create an intellectual credit agreement as a team

### Month 7 (Mar.)

- Draft outline for the product that your team aims to create
- Begin generating publication-quality figures
- Prepare datasets for publication (if relevant)
    - Consider FAIR and CARE data practices

### Month 8-9 (Apr./May)

- Draft publishable dataset
- Team product ready to report on (internally) to SSECR fellows & instructors
- Intellectual credit contributions table completed

:::
