
Generative artificial intelligence (hereafter "genAI") can feel unavoidable--particularly in data science contexts. As the instructors of the course, we don't feel it's appropriate to dictate how or where you use genAI, though for the purposes of this course, we do have some recommendations.

Broadly, we can divide genAI considerations into two bins: using it by/for yourself versus using it with your project group.

:::{.panel-tabset}
#### Individual Use

What "responsible" genAI use actually consists of is ill-defined (at time of writing), but broadly many people can agree that:

1. **You should use genAI to _augment_ your learning, _not_ replace it!**

We hope that SSECR leaves you with a set of skills that are useful in many facets of your career going forward and developing "muscle memory" through repetitive practice is a critical part of that.

2. **All genAI outputs should be checked before being relied upon.**

Ideally, use of genAI should be start and end with a human. You should carefully consider the prompt and inputs that you use and check the output to make sure it is exactly what you expected. Both pieces of this can be tricky to do if you are not already proficient in the skill for which you're using genAI so keep that in mind. Even if you possess that skill, remember to still set aside time to review genAI outputs before accepting them.

#### Project Group Use

GenAI use in a team context is, in some ways, stickier than when considering using it for yourself. Your group will need to reach consensus on how/whether to use genAI for project work because, ultimately, all of your names will be on any products the group produces.

:::{.callout-note}
### Discussion Tools

Modules in this course will provide you with tools for engaging in meaningful dialogue with your group! If you feel unprepared to discuss as a group, _don't worry_, we'll help you gain the skills to feel more comfortable within the first few weeks of the course.
:::

So, we recommend the following:

1. **Discuss genAI comfortability with the group <u>as early as possible</u>!**

Get specific! Are you okay with using it to refactor code? What about writing first draft text? Brainstorming research questions?. You'll want to have chatted about this stuff _before_ someone uses genAI in a way that feels reasonable to them but deeply unreasonable to another group members. Think about ways to ask for consent and record that consent and listen from a place of trying to understand. If you normally use genAI for every facet of your work, you'll likely have to use it less to compromise with the group. If you don't use genAI at all, you may need to consider which use-cases you are more comfortable with the group using genAI for.

2. **Document your use of genAI!**

Write down information on how you use genAI _as you use it._ This might include what models you used, when you used them, the specific text of the prompt you used, or other related factors. This documentation will be useful when you write up an eventual product and will also help make sure that your group is using genAI in ways that are consistent with your discussion about how community norms in this sphere (see point \#1). Writing it down as you go will help make sure you don't forget that you used genAI for some piece of the project months later when you're writing it up.

3. **Disclose your use of genAI in any/all products that you create!**

If you document your use of genAI (see point \#2), this should be fairly straightforward! You want to avoid getting a paper rejected because you said you used genAI for "manuscript writing" so leaning on your specific documentation of genAI use will help you be completely forthright about your use of these tools. This will help avoid any awkward or professionally-damaging situations around undisclosed genAI use.

:::
