## Communicating Before Publication

First of all, you all do this--talking to your advisor, a friend, etc. Here are some tips that might be useful when thinking about getting this out publicly. [**Why is it difficult to talk about early-stage research**](https://richardberks.co.uk/blog/how-to-talk-about-the-impact-of-basic-research/)? Many of you have research that isn't yet complete. But you can (and should!) be encouraged to share it share it!

### Connecting With Your Press Office:

Tips from Harrison Tassoff, science writer for the UCSB Current.

- If you don't tell us about it, we don't know about it
- We want to share your work, and we want to get it right
- Don't know whom to contact? Email someone that looks right. We can always direct you to the right person
- Not every paper/grant/award is news. But, if in doubt, email us
- Journalists can't let you see a rough draft. Public Information Officers (those that work for the University, etc) generally will
- When you first contact a writer, please give us:
    - A brief description of the research, what you found and why it matters (\~1-2 paragraphs)
    - The most recent version of the manuscript
    - The journal name
    - The embargo date and time (best guess is fine)
    - What other institutions are involved and if they're issuing a release
