### Tool Highlight: Polls & Think-Pair-Share

**Polls** are useful tools for collecting input. They can be deployed synchronously or asynchronously, anonymously or not. Consider using them before a meeting to understand the group's starting point and help shape the content. Use them during a meeting to collect real time data. Or use them after a meeting to gather feedback. Zoom's integrated polling is simple but effective. Other options include slido, mentimeter, and google forms.

**Think-Pair-Share** is a common teaching tool that is very effective for engaging groups in reflection and discussion. Starting with individual reflection suits those who like to process ideas in quiet. Discussing in pairs allows everyone to share their ideas and learn from each other before highlights are lifted up to the whole group. "[1-2-4-all](https://www.liberatingstructures.com/1-1-2-4-all/)" (sometimes also called "think-pair-square-share") is a related microstructure that can be used to rapidly share and sift ideas in any group of eight or more people. In a virtual setting, to simplify breakout room logistics, it's easiest to just have three levels: individual, breakout groups of 2 or more people, and whole group.
