## Why Communicate Your Findings?

> "Science speaks for itself." "Good work will get recognized on its own." "It's the journal/university/lab's job to share my results."

All are common excuses that keep researchers from taking the initiative to communicate their science. But sharing your work is an essential part of maximizing it's impact.

Some evidence ([like this paper](https://journals.sagepub.com/doi/10.1177/1077699014550092)) shows that tweeting the results of a paper leads to more citations. Other studies disagree, but find that total *engagement* still increases when work is shared ([from this paper](https://www.nature.com/articles/d41586-024-00922-y)). That engagement has rewards!

Putting your work out in public let's others find it. That could lead to new collaborators, more citations, an article in the press, or even money from funders. If that work hides behind a paywall, it's much harder for someone to find it!

Think about this--one [SBC LTER researcher was walking on the beach](https://www.independent.com/2022/10/08/chance-encounter-on-beach-leads-to-3-million-for-santa-barbara-coastal-research/), doing drone surveys. Someone stopped to chat, and they explained their research to them. A few weeks later, the SBC LTER had *three million more dollars*, after that person decided to donate to the cause. All from SciComm!

Today, we're going to walk through turning your own research into an elevator pitch, a tight, concise explanation of what you've done. The process of creating an elevator pitch will give you the tools necessary to adapt your message to a variety of different audiences and formats.
