## Choosing search terms

:::{.callout-tip icon="false" collapse="false"}
### {{< fa brain >}} Learning Objectives

After completing this topic you will be able to: 

- <u>Understand</u> how research questions map to the data that will be needed
- <u>Refine</u> your synthesis groups research question the terms of a data query

:::

The answer to any research question is found in data, and many questions are formulated with specific data in mind. Synthesis questions are often formulated with limited data in-hand and an intention to scale up the question to "all the available data." Therefore, synthesis projects usually begin with a process of data discovery - finding datasets that can be used to answer the question.

Venn diagram - All available data, data that can answer the question

Finding the data you need for synthesis isn't always easy, but starting with a clear research question helps because you can map it to criteria and search terms that you'll use. This is because research questions and datasets contain the same conceptual elements. They both always include:

- Variables observed, measured, or estimated (precipitation, gas flux, abundance)
- Observational units - the actual thing being observed or measured (an ecosystem process, a layer of soil, animals, part of a tree)

In addition, they both often have:

- Groups of some kind (known or hypothesized - treatments, taxonomic group, functional type)
- A temporal dimension (explicit or not - time of observation)
- A spatial dimension (explicit or not - location of observation)

Translating these concepts as they are written in your research question to the attributes of the data you will search will help you find useful datasets more efficiently.

+------------------------------------+-------------------------------+-----------------------------------------------------------+
| Research question                  | Conceptual mapping            | Data search criteria                                      |
+====================================+===============================+===========================================================+
| Does species richness increase or  | Does variable X increase or   | - **Variables:** presence/absence, richness (# species)   |
| decrease after disturbance?        | decrease with time?           | - **Obs. units:** sampling area w/ known disturbance time |
|                                    |                               | - **Groups:** maybe?                                      |
|                                    |                               | - **Temporal:** time since disturbance                    |
+------------------------------------+-------------------------------+-----------------------------------------------------------+
| Are forests or deserts more        | Is group 1 or group 2 more    | - **Variables:** VPD, NPP, evapotranspiration rate, etc.  | 
| sensitive to vapor pressure        | strongly related to variable  | - **Obs. units:** site meteorology & ecosystem processes  |
| deficit?                           | X?                            | - **Groups:** forest ecosystems, desert ecosystems        |
|                                    |                               | - **Temporal:** probably (processes vary over time)       |
+------------------------------------+-------------------------------+-----------------------------------------------------------+
| Is the latitudinal gradient in     | Is the relationship between   | - **Variables:** body length, mass, capture location      | 
| small mammal body size changing?   | variable 1 and variable 2     | - **Obs. units:** individual small mammals                |
|                                    | changing?                     | - **Groups:** species? functional group? year captured?   |
|                                    |                               | - **Temporal:** yes, at least two time periods            |
|                                    |                               | - **Spatial:** yes, need a latitude gradient              |
+------------------------------------+-------------------------------+-----------------------------------------------------------+


::::{.callout-warning icon="false"}
### {{<fa rocket >}} Activity: Map your research question to data search terms

Get into project groups and distill your research questions down to a conceptual mapping like the ones above.

1. What variables and observational units are of interest?
2. Will you be comparing groups within the data?
3. Temporal dimensions?
4. Spatial dimensions?

:::

Once you have an idea of your search terms, it is time to think about **where to search for data**. 