## Introduction to Quarto

:::{.callout-tip icon="false" collapse="false"}
### {{< fa brain >}} Learning Objectives

After completing this topic you will be able to: 

- <u>Identify</u> the three fundamental elements of a typical notebook
- <u>Use</u> Markdown syntax to accomplish text styling
- <u>Create</u> notebooks that include a blend of plain text and embedded code chunks
- <u>Make</u> a Quarto website
- <u>Define</u> the purpose of GitHub Actions
- <u>Deploy</u> a notebook with GitHub Pages

:::

### LTER Workshop Materials

The workshop materials we will be working through live [here](https://lter.github.io/workshop-quarto/) but for convenience we have also embedded the workshop directly into the SSECR course website (see below).

 ```{=html}
<iframe src="https://lter.github.io/workshop-quarto/" height="550" width="800" style="border: 1px solid #2e3846;"></iframe>
```

::::{.callout-warning icon="false"}
### {{<fa rocket >}} Activity: Making a Team / Personal Website

Note that you _do not_ need to keep your website up after you make it if you already have one or don't want one but this activity will still be good practice regardless.

Eventually you will likely want a team-wide website. You are absolutely welcome to make this during today's module but because the first draft must be made by a single person, **all but one member of your group must work on individual sites instead**. You can (and should!) revisit your site as a group to make sure all of you are happy with it but creating individual sites today will help all of you develop 'muscle memory' in this arena.

::::