## Online Meetings

:::{.callout-tip icon="false" collapse="false"}
### {{< fa brain >}} Learning Objectives

- <u>Explain</u> methods for improving the experience of virtual participants on hybrid teams

:::

Online meetings benefit from all the same considerations as in person meetings, plus a little extra care and planning. Keeping your team engaged is doubly challenging in a virtual setting: our computers are full of distractions (email! notifications! internet rabbit holes!) _and_ as the facilitator, it's harder to tell whether participants are engaged when all you have to go on is a small video window. Managing people's energy and attention and creating opportunities for real human connection are real challenges. On the flip side, online meetings allow distributed teams to stay connected and can provide a dynamic and rich platform for shared work.

In addition to the general tips above, in online settings:

1. Be thoughtful and equitable when scheduling across time zones
2. Develop online meeting norms for your team and enforce them (e.g., use of chat, indicating you want to speak)
3. Ask a team member to help you monitor the chat and assist participants with tech or connectivity challenges
4. Encourage personal connection (e.g., with check ins, invitations to have video on)
4. Check engagement regularly
5. Provide breaks (bio breaks, silence, invitations to step away from the screen for reflection)
6. Make video optional 
7. Take advantage of tech tools (breakout rooms, polls, shared notes, virtual whiteboards, recording, transcription, etc.)
