## Ensuring Equitable Access to Participation

To tap diverse perspectives and catalyze productivity and creative problem-solving, we need to design meetings (and projects) so <u>everyone</u> can participate fully, rather than just a few. When tackling complex challenges, voices from the edge are often critical to uncovering new insights and approaches. Democratizing participation doesn't have to be all about controlling the dominant voices in a group; with thoughtful planning and some simple tools, you can design any conversation so that everyone can contribute.

A few simple techniques can help:
 
1. Mix up the format, e.g., combining silent reflection, round robin, breakout groups, plenary, and/or "liberating structures" (more on these below)
2. Offer different channels for information sharing - verbal, nonverbal, written, visual, informal, formal
3. Track and stack who wants to speak 
4. Invite, amplify, and credit "quieter" voices 
5. Use active listening - reflect back what you think you are hearing in simple terms and check your assumptions regularly

Be creative and empathetic when you design your agenda. Think about your participants and what is going to help _all of them_ participate fully and creatively. Beyond the thinking preferences, you may also want to consider these other dimensions of diversity when planning your process design and facilitation:

- Introverts vs. extroverts
- Visual, auditory and kinesthetic learners
- Disciplinary diversity
- Career stage
- Language
- Time zone (for geographically distributed teams)
