## What is Project Management?

:::{.callout-tip icon="false" collapse="false"}
### {{< fa brain >}} Learning Objectives

After completing this topic you will be able to: 

- <u>Identify</u> key elements of project management frameworks

:::
 
There are dozens of formal project management frameworks/approaches, most of which come out of industries (such as software development, construction, and manufacturing) that require teams of people to work together with efficiency and accountability. You've probably heard the names tossed around: Agile, Scrum, Lean Sigma Six, Kanban, etc. There are whole industries devoted to training project managers and developing apps to support them.

The trick, for scientific research projects, is to identify the approaches that also allow questions and goals to evolve along the way – and that don't require a full-time project manager to implement.

Some common elements of project management schemes include:

:::{.panel-tabset}
### Logical Step Sequence

| Industry Outcome | Science Outcome |
|:-|:-|
| Ensure needed resources/people tools are available when needed | Know which skills are needed when; know what form the output of each script/analysis needs to take |

### Identify Dependencies

| Industry Outcome | Science Outcome |
|:-|:-|
| Avoid supply chain lags | Know what data you need and when you need them |

### Clarify Responsibilities

| Industry Outcome | Science Outcome |
|:-|:-|
| Document productivity and responsibility | Avoid duplication of effort; keep the project moving; support authorship/credit agreements |

### Mitigate Risk

| Industry Outcome | Science Outcome |
|:-|:-|
| Know when to abort or revise project goals | Assess threats to project success early and make a plan B |

:::

