## Meta-Analysis

:::{.callout-tip icon="false" collapse="false"}
### {{< fa brain >}} Learning Objectives

After completing this topic you will be able to: 

- <u>Paraphrase</u> how "meta-analysis" differs from other forms of statistics

:::
 
Many synthesis projects are able to find the original data of each study, harmonize that data, and then perform standard analyses on that synthesized data. However, in some cases you may find that the data used in different projects are not directly comparable. For instance, if you want to know what the effect of restoration methods are on forest recovery you might not be able to simply combine data from different studies that use widely different restoration methods, data collection methods, and have different forest community compositions. In such cases **you can use meta-analysis to compare the *results* of different studies rather than using their data**. Meta-analysis is named the way it is because it is an analysis of prior analyses.

To perform meta-analysis you'll need to calculate an "effect size" for all studies you'd like to include. An effect size captures the *direction* and *magnitude* of the relationship analyzed in each original study. If you use a standard effect size calculation for each stud, you'll make it possible to directly compare results across these studies (even if context differs among them!). Note that some people disagree with the word "effect" in "effect size" because it suggests a causal relationship; for our purposes, let's consider 'effect' to be inclusive of correlative relationships and ignore the possible implication of causality.

In order to calculate these effect sizes you'll need to extract the following information from each study:

1.  A measure of the 'central tendency' of the response
    -   Often the arithmetic mean but can also be a proportion or a correlation
    -   You'll need to do this separately for any groups within the study
2.  A measure of the variation in the response
    -   Typically standard deviation
3.  The sample size of the response

Once you have that information, you can calculate effect sizes for the various groups in each study. Note that the importance of this information to meta-analyses should also highlight <u>how vital it is that you report this information in your own research</u>! Doing so will enable future meta-analyses to include your study and increase the scientific impact of your work as well as its professional benefits to you.

One such effect size is Cohen's *d* and is a reasonable effect size for quantifying the difference in means between two groups. In order to perform this calculation you simply need the mean, standard deviation, and sample size for two groups. Let's check out an example to demonstrate.

```{r meta-cohen-d}
# Load needed library
library(esc)

# Calculate Cohen's d
calc_effect <- esc::esc_mean_sd(grp1m = 50, grp2m = 60, 
                                grp1sd = 10, grp2sd = 10, 
                                grp1n = 50, grp2n = 50)

# Check out output
calc_effect
```

Note that Cohen's *d* is just one effect size available to you and others may be more appropriate in certain contexts. Just like any other metric, which effect size you choose is a mix of your scientific intuition and appropriateness for the content of your data. For a deeper dive into the breadth of effect size considerations available to you, see [the relevant chapter](https://bookdown.org/MathiasHarrer/Doing_Meta_Analysis_in_R/effects.html#effects) of the *Doing Meta-Analysis in R* online book.

After you've calculated all relevant effect sizes--using your chosen flavor of effect size--the "actual" meta-analysis is nearly finished. Simply create a graph of the effect sizes with error bars indicating confidence intervals (included by default in most effect size functions). Where the error bars overlap among studies, there is no significant difference between those effect sizes. Conversely, where the error bars *do not* overlap among studies the effect sizes do significantly differ indicating that the studies results' differ for the data used to calculate the effect size.
