## Science of Team Science

Research in management, organizational behavior, and psychology  has long focused on the performance of teams–often in military, healthcare and industrial contexts. While many aspects of this work are also relevant to scientific teams, there are some key differences having to do with differences in context, leadership, and incentives. In the early 2000's–as collaboration in science increased–the need for empirical research into the workings of science teams became apparent. The field of "science of team science" or SiTS was launched in 2006 with a conference at the National Institutes of Health (Stokols et al. 2008).

A National Academies study on the _Science of Team Science_ (NRC 2015) assembled the existing evidence base and launched a flurry of research into how team composition, coordination, support, and organizational context could improve outcomes for science teams. A new National Academies study on _Research and Application in Team Science_ is currently in progress. Our goal here is not to review the whole field, but to provide a framework for thinking about the team functioning and process and to identify some key team science practices that are supported by both research and practical experience.
