## Tools to Support the Thinking You Need 

(D=divergent, E=emergent, C=convergent)

| **Microstructure** | **Stage** | **Purpose** | **How It Works** | **Tips & Traps** |
|:---|:---:|:------------|:--------------------|:---------------|
| [Brainwriting](https://gamestorming.com/brainwriting/) or brainstorming | D | Surface and elaborate ideas | Brainstorm ideas in a google doc or virtual whiteboard (or on index cards or sticky notes in person); read and add to each other's ideas; discuss | Follow up with affinity mapping as you move into emergent thinking |
| [Rotating Stations](http://www.liberatingstructures.com/11-shift-share/) | D | Spread good ideas and make informal connections | Set up stations with experts or innovators who can present information and engage discussion; group members circulate to learn, ask questions, or provide feedback | Keep the overall session short so that it's not too fatiguing for presenters who will have to repeat their spiel many times |
| [User Experience Fishbowl](http://www.liberatingstructures.com/18-users-experience-fishbowl/) (a riff on panel discussion) | DE | Draw out and contrast different perspectives from experts or interested parties  | Experts with direct experience of the challenge at hand are invited to engage each other in conversation at the center of a circle; the rest of the group are audience to their conversation; audience and facilitator can suggest things for them to discuss | Avoid falling back on traditional formats where panelists talk to the audience rather than each other - the power of the fishbowl is the deep way in which the experts can engage each other |
| Horizon scanning / futures thinking | DE | Detect emerging trends, issues, or research opportunities | Define your scope; consult outside sources of data and expertise or brainstorm within the group to identify emerging trends, events, and weak signals of future change that may affect the question / topic you have defined | Set a timeframe that's far enough out to encompass important uncertainties but not so far that forecasting becomes overly speculative |
| [Affinity Map](https://gamestorming.com/?s=affinity+map) (clustering) | E | Surface ideas, detect patterns, and analyze | Brainstorm ideas using sticky notes on a wall or virtual whiteboard; cluster into categories | Follow up with prioritization of ideas within clusters as you move into convergent thinking |
| Conceptual models | E | Build a shared representation of the system | Co-develop a figure or diagram that encapsulates your collective understanding of the focal problem or system  | Consider mind maps, flow charts, system diagrams; Consider having several small groups attempt this in parallel and compare results |
| [World Cafe conversations](http://www.liberatingstructures.com/17-conversation-cafe/) | E | Engage everyone in making sense of profound challenges | Ask for a volunteer to host each table; use a talking object; Go-around 1: share what you are thinking, feeling, or doing about the theme or topic; Go-around 2: share your thoughts and feelings after having listened to others; Open conversation; Go-around 4: "takeaways" | Start with a clear question or prompt for discussion; Share the agreements and ask hosts to gently facilitate adherence |
| [What, So What, Now What](https://www.liberatingstructures.com/9-what-so-what-now-what-w/) | EC | Make sense of past progress or experiences and decide on future actions | What - As a group, compile the facts and observations relevant to the context; So What - Reflect on the facts and their implications, identify patterns, generate hypotheses; Now What - Draw conclusions - What actions make sense? | Be firm in calling out opinions being passed off as facts in the What stage. Stick to what is observable. |
| Polling | EC | Rank alternatives | Decide how many votes per person; In person - use sticky dots; Virtually - use +1s in a google doc or a digital polling tool (e.g., Zoom, Mural, slido) | Before you start - clarify how you will use the results - are you gathering information or taking a vote to make a decision? |
| Feasibility x impact matrix | C | Compare alternatives | Discuss and agree on definitions for two criteria for evaluating ideas: feasibility of implementation and impact potential; Rate each idea against these two axes and map onto 2x2 grid | How you define the axes must be clear and agreed upon by everyone before you start |
| [Fist to Five](https://gamestorming.com/five-fingered-consensus/) / Gradient of Agreement | C | Assess degree of consensus; seek closure | Use when ready to close a discussion or make a decision; Invite participants to rate their level of agreement with a proposal on a scale of 0-5; Five fingers means "absolute, total agreement or support" and a fist means "complete opposition" | If you have some 1s and 2s, more discussion is needed - ask them to explain their concerns or questions |
| Open discussion | DEC | Group inquiry, sensemaking, and/or decision-making | Clearly define the scope; set agreements for inclusive discussion; invite discussion about the topic at hand; capture ideas and questions; listen for when the group is ready to converge | Keep track of side topics (e.g. in a "bike rack") and make time to come back to them, but don't let them derail |
| Breakout groups | DEC | Engage everyone deeply; avoid groupthink | Define the scope and intended outcomes; set a time limit; assign roles (facilitator, notetaker, reporter); model what you want in the report out | Consider whether all groups should work with the same prompts or different aspects of the problem |
| Chart writing or whiteboarding | DEC | Reflect participant's viewpoints back to the group | On a virtual or physical chart or whiteboard, capture key points in the discussion so everyone can see them | Use speakers' own words; if the comment is long or complex, ask the speaker to give you a headline you can capture |
| [1,2,4,all](https://www.liberatingstructures.com/1-1-2-4-all/) | DEC | Engage everyone in generating questions, ideas, and suggestions | Individual reflection; Pair share; Two pairs combine and share as a group of 4; Small groups share highlights with whole group | Emphasize novel ideas and distinctions for divergence; common themes and emerging insights for emergence and convergence |
| Round robin / go around | DEC | Hear from everyone; get starting positions on the table | Everyone answers the same prompt. Alternatives to going in order: each speaker calls on someone else after they have shared; popcorn-style - people share in the order that they feel moved to speak | Do not allow discussion until everyone has responded to the initial prompt |
