## Making a Workflow Plan

:::{.callout-tip icon="false" collapse="false"}
### {{< fa brain >}} Learning Objectives

After completing this topic you will be able to: 

- <u>Identify</u> major needs and possible obstacles in your group's data workflow

:::

_Before_ you start actually developing your data workflow (or early in the development process), it is a good idea to develop a plan for what data manipulation needs to be done. Just like with visualization, it can be helpful to literally sketch out this plan so that you think through the major points in your data pipeline before beginning to write code that turns out to not be directly related to your core priorities. Consider the discussion below for some leading questions that may help you articulate your group's plan for your data.

::::{.callout-warning icon="false"}
### {{<fa rocket >}} Activity: Discuss Workflow Plan

With your project group, discuss the following questions:

- What needs to be done to make your starting data files comparable?
    - Consider units, taxonomic resolution, spatial/temporal granularity, etc.
- Once the original data files are comparable, what else needs to be done?
    - Do you need to calculate index metrics? Change the 'shape' of the data? Aggregate to a particular spatial/temporal resolution or sampling intensity?
- How can you make your workflow less repetitive / more efficient?
    - Reducing redundancy makes integrating new ideas _dramatically_ easier
- How easy will it be to maintain or revisit this code workflow?
- How can you change the workflow now to make life easier for 'future you'?

::::
